# Generated by Django 2.1 on 2020-08-28 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200828_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fin_oferta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Fin de la Oferta'),
        ),
        migrations.AddField(
            model_name='product',
            name='imagen_oferta',
            field=models.ImageField(blank=True, null=True, upload_to='Ofertas de la Portada', verbose_name='Adjunta la Imagen de la Oferta'),
        ),
        migrations.AddField(
            model_name='product',
            name='oferta_categoria',
            field=models.BooleanField(blank=True, null=True, verbose_name='¿Tiene Oferta la Categoria?'),
        ),
        migrations.AddField(
            model_name='product',
            name='oferta_subcategoria',
            field=models.BooleanField(blank=True, null=True, verbose_name='¿Tiene Oferta  la SubCategoria?'),
        ),
    ]
