# Generated by Django 2.1 on 2020-09-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200904_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fisico',
            field=models.BooleanField(blank=True, null=True, verbose_name='¿El producto es Físico?'),
        ),
    ]
