# Generated by Django 2.1 on 2020-09-08 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200908_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='nuevo',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='¿Producto es Nuevo?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='oferta',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='¿Tiene alguna Oferta?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='oferta_categoria',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='¿Tiene Oferta la Categoria?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='oferta_subcategoria',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='¿Tiene Oferta  la SubCategoria?'),
        ),
    ]
