# Generated by Django 2.1 on 2020-09-09 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200908_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='entrega',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='¿Dias promedio de entrega?'),
        ),
    ]
