# Generated by Django 2.1 on 2020-09-10 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0003_auto_20200910_1729'),
        ('core', '0008_product_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='banner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_banner', to='header.Header', verbose_name='Campaña'),
        ),
    ]
