# Generated by Django 2.1 on 2020-09-11 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_product_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='banner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='get_banner', to='header.Header', verbose_name='Campaña'),
        ),
    ]
