# Generated by Django 2.1 on 2020-09-11 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0004_auto_20200911_0949'),
        ('core', '0010_auto_20200910_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='banner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='get_banners', to='header.Header', verbose_name='Campaña'),
        ),
    ]
