# Generated by Django 2.1 on 2020-09-13 19:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_product_url_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='titular',
            field=ckeditor.fields.RichTextField(max_length=200, verbose_name='Titular'),
        ),
    ]
