# Generated by Django 2.1 on 2020-08-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='color',
            field=models.CharField(max_length=200, null=True, verbose_name='¿Lo quieres Blanco, Negro o Color?'),
        ),
    ]
