# Generated by Django 2.1 on 2020-08-18 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_link_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='color',
        ),
    ]
