# Generated by Django 2.1 on 2020-09-10 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0002_auto_20200910_1708'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='header',
            options={'ordering': ['-created'], 'verbose_name': 'Banner', 'verbose_name_plural': 'Banners'},
        ),
        migrations.AlterField(
            model_name='header',
            name='name',
            field=models.CharField(default='Campaña', max_length=100, verbose_name='Nombre del Banner'),
        ),
        migrations.AlterField(
            model_name='header',
            name='titulo1_banner',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Titulo del Banner'),
        ),
        migrations.AlterField(
            model_name='header',
            name='titulo2_banner',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='SubTitulo del Banner'),
        ),
        migrations.AlterField(
            model_name='header',
            name='titulo3_banner',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='SubTitulo2 del Banner'),
        ),
    ]
