# Generated by Django 2.1 on 2020-09-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0003_auto_20200910_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='style_google',
            field=models.CharField(blank=True, choices=[('googleColor', 'Color'), ('googleBlanco', 'Blanco'), ('googleNegro', 'Negro')], max_length=45, null=True, verbose_name='Color del Google?'),
        ),
        migrations.AlterField(
            model_name='header',
            name='style_instagram',
            field=models.CharField(blank=True, choices=[('instagramColor', 'Color'), ('instagramBlanco', 'Blanco'), ('instagramNegro', 'Negro')], max_length=45, null=True, verbose_name='Color del Instagram?'),
        ),
    ]
