# Generated by Django 2.1 on 2020-09-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0004_auto_20200911_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Slider')),
                ('imagen_fondo_slider', models.ImageField(blank=True, null=True, upload_to='Slider Fondo', verbose_name='Adjunta la Imagen del Fondo')),
                ('imagen_prodcuto_slider', models.ImageField(blank=True, null=True, upload_to='Slider Producto', verbose_name='Adjunta la Imagen del Prodcuto')),
                ('style_tex_slider', models.CharField(blank=True, choices=[('slideOpcion1', 'Opción 1'), ('slideOpcion2', 'Opción 2')], max_length=45, null=True, verbose_name='Selecciona Ubicacion del Texto')),
                ('titulo1_slider', models.CharField(blank=True, max_length=100, null=True, verbose_name='Titulo del Slider')),
                ('titulo2_slider', models.CharField(blank=True, max_length=100, null=True, verbose_name='SubTitulo del Slider')),
                ('titulo3_slider', models.CharField(blank=True, max_length=100, null=True, verbose_name='SubTitulo2 del Slider')),
                ('style_imagen_top', models.IntegerField(blank=True, null=True, verbose_name='¿Desplazamiento de la imagen Vertical?')),
                ('style_imagen_rigth', models.IntegerField(blank=True, null=True, verbose_name='¿Desplazamiento de la imagen a la Derecha')),
                ('style_imagen_left', models.IntegerField(blank=True, null=True, verbose_name='¿Desplazamiento de la Imagen a la Izquierda')),
                ('style_imagen_widgth', models.IntegerField(blank=True, null=True, verbose_name='¿Tamaño de la imagen')),
                ('style_text_top', models.IntegerField(blank=True, null=True, verbose_name='¿Desplazamiento del texto Vertical?')),
                ('style_text_rigth', models.IntegerField(blank=True, null=True, verbose_name='¿Desplazamiento del texto a la Derecha')),
                ('style_text_left', models.IntegerField(blank=True, null=True, verbose_name='¿Desplazamiento del texto a la Izquierda')),
                ('style_text_widgth', models.IntegerField(blank=True, null=True, verbose_name='¿Tamaño del texto')),
                ('boton', models.BooleanField(default=True, verbose_name='¿El producto es Físico?')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Enlace')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Sliders',
                'ordering': ['-created'],
            },
        ),
    ]
