# Generated by Django 2.1 on 2020-09-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0005_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='style_imagen_left',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='¿Desplazamiento de la Imagen a la Izquierda'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='style_imagen_rigth',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='¿Desplazamiento de la imagen a la Derecha'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='style_imagen_top',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='¿Desplazamiento de la imagen Vertical?'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='style_imagen_widgth',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='¿Tamaño de la imagen'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='style_tex_slider',
            field=models.CharField(blank=True, choices=[('slideOpcion1', 'Opción 1'), ('slideOpcion2', 'Opción 2')], help_text='Opción 1: Imagen a la derecha y texto izquierda Opción 2: Imagen a la izquierda y texto derecha', max_length=45, null=True, verbose_name='Selecciona Ubicacion del Texto'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='style_text_left',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='¿Desplazamiento del texto a la Izquierda'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='style_text_rigth',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='¿Desplazamiento del texto a la Derecha'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='style_text_top',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='¿Desplazamiento del texto Vertical?'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='style_text_widgth',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='¿Tamaño del texto'),
        ),
    ]
