# Generated by Django 2.1 on 2020-09-12 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0007_auto_20200911_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Producto')),
                ('clave', models.CharField(max_length=100, verbose_name='Clave del Producto')),
                ('imagen1', models.ImageField(blank=True, null=True, upload_to='Visor1', verbose_name='Adjunta Imagen Visor')),
                ('imagen2', models.ImageField(blank=True, null=True, upload_to='Visor2', verbose_name='Adjunta Imagen Visor')),
                ('imagen3', models.ImageField(blank=True, null=True, upload_to='Visor3', verbose_name='Adjunta Imagen Visor')),
                ('imagen4', models.ImageField(blank=True, null=True, upload_to='Visor4', verbose_name='Adjunta Imagen Visor')),
                ('imagen5', models.ImageField(blank=True, null=True, upload_to='Visor5', verbose_name='Adjunta Imagen Visor')),
                ('imagen6', models.ImageField(blank=True, null=True, upload_to='Visor6', verbose_name='Adjunta Imagen Visor')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Visor',
                'verbose_name_plural': 'Visors',
                'ordering': ['-created'],
            },
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ['created'], 'verbose_name': 'Slider', 'verbose_name_plural': 'Sliders'},
        ),
        migrations.AlterField(
            model_name='slider',
            name='boton',
            field=models.BooleanField(default=True, verbose_name='¿Quieres colocar el boton?'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='color_titulo1',
            field=models.CharField(blank=True, choices=[('#FFFFFF', 'Blanco'), ('#C0C0C0', 'Plateado'), ('#808080', 'Gris'), ('#000000', 'Negro'), ('#FF0000', 'Rojo'), ('#800000', 'Granada'), ('#FFFF00', 'Amarillo'), ('#808000', 'Oliva'), ('#00FF00', 'Lima'), ('#008000', 'Verde'), ('#00FFFF', 'Aqua'), ('#008080', 'Teal'), ('#0000FF', 'Azul'), ('#000080', 'Navy'), ('#FF00FF', 'Fucsia'), ('#800080', 'Purpura')], max_length=45, null=True, verbose_name='Selecciona Color del Titulo'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='color_titulo2',
            field=models.CharField(blank=True, choices=[('#FFFFFF', 'Blanco'), ('#C0C0C0', 'Plateado'), ('#808080', 'Gris'), ('#000000', 'Negro'), ('#FF0000', 'Rojo'), ('#800000', 'Granada'), ('#FFFF00', 'Amarillo'), ('#808000', 'Oliva'), ('#00FF00', 'Lima'), ('#008000', 'Verde'), ('#00FFFF', 'Aqua'), ('#008080', 'Teal'), ('#0000FF', 'Azul'), ('#000080', 'Navy'), ('#FF00FF', 'Fucsia'), ('#800080', 'Purpura')], max_length=45, null=True, verbose_name='Selecciona Color del Subtitulo'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='color_titulo3',
            field=models.CharField(blank=True, choices=[('#FFFFFF', 'Blanco'), ('#C0C0C0', 'Plateado'), ('#808080', 'Gris'), ('#000000', 'Negro'), ('#FF0000', 'Rojo'), ('#800000', 'Granada'), ('#FFFF00', 'Amarillo'), ('#808000', 'Oliva'), ('#00FF00', 'Lima'), ('#008000', 'Verde'), ('#00FFFF', 'Aqua'), ('#008080', 'Teal'), ('#0000FF', 'Azul'), ('#000080', 'Navy'), ('#FF00FF', 'Fucsia'), ('#800080', 'Purpura')], max_length=45, null=True, verbose_name='Selecciona Color del Subtitulo2'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='style_imagen_left',
            field=models.CharField(blank=True, help_text='Recuerda colocar el %', max_length=100, null=True, verbose_name='Imagen Left?'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='style_imagen_rigth',
            field=models.CharField(blank=True, help_text='Recuerda colocar el %', max_length=100, null=True, verbose_name='Imagen Rigth?'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='style_imagen_top',
            field=models.CharField(blank=True, help_text='Recuerda colocar el %', max_length=100, null=True, verbose_name='Imagen Top?'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='style_imagen_widgth',
            field=models.CharField(blank=True, help_text='Recuerda colocar el %', max_length=100, null=True, verbose_name='Imagen Widgth?'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='style_text_left',
            field=models.CharField(blank=True, help_text='Recuerda colocar el %', max_length=100, null=True, verbose_name='Texto Left?'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='style_text_rigth',
            field=models.CharField(blank=True, help_text='Recuerda colocar el %', max_length=100, null=True, verbose_name='Texto Rigth?'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='style_text_top',
            field=models.CharField(blank=True, help_text='Recuerda colocar el %', max_length=100, null=True, verbose_name='Texto Top?'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='style_text_widgth',
            field=models.CharField(blank=True, help_text='Recuerda colocar el %', max_length=100, null=True, verbose_name='Texto Widgth?'),
        ),
    ]
