# Generated by Django 2.1 on 2020-09-12 13:51

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0008_auto_20200911_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
    ]
