# Generated by Django 2.1 on 2020-09-12 13:54

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0009_slider_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='color',
        ),
        migrations.AlterField(
            model_name='slider',
            name='color_titulo1',
            field=colorfield.fields.ColorField(blank=True, default='#000000', max_length=18, null=True, verbose_name='Selecciona Color del Titulo'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='color_titulo2',
            field=colorfield.fields.ColorField(blank=True, default='#000000', max_length=18, null=True, verbose_name='Selecciona Color del Subtitulo'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='color_titulo3',
            field=colorfield.fields.ColorField(blank=True, default='#000000', max_length=18, null=True, verbose_name='Selecciona Color del Subtitulo2'),
        ),
    ]
