# Generated by Django 2.1 on 2020-09-12 18:45

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0012_auto_20200912_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='barrainferior',
            field=colorfield.fields.ColorField(blank=True, default='#333', max_length=18, null=True, verbose_name='Selecciona Color del Barra Inferior'),
        ),
        migrations.AlterField(
            model_name='header',
            name='barrasuperior',
            field=colorfield.fields.ColorField(blank=True, default='#333', max_length=18, null=True, verbose_name='Selecciona Color de la barra Superior'),
        ),
        migrations.AlterField(
            model_name='header',
            name='textoinferior',
            field=colorfield.fields.ColorField(blank=True, default='#333', max_length=18, null=True, verbose_name='Selecciona Color del Texto Inferior'),
        ),
    ]
