# Generated by Django 2.1 on 2020-09-13 16:50

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0014_auto_20200912_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='barrainferior',
            field=colorfield.fields.ColorField(blank=True, default='#000000', max_length=18, null=True, verbose_name='Selecciona Color del Barra Inferior'),
        ),
        migrations.AlterField(
            model_name='header',
            name='barrasuperior',
            field=colorfield.fields.ColorField(blank=True, default='#000000', max_length=18, null=True, verbose_name='Selecciona Color de la barra Superior'),
        ),
    ]
