# Generated by Django 2.1 on 2020-09-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0015_auto_20200913_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visor',
            name='imagen1',
            field=models.ImageField(blank=True, null=True, upload_to='Visor', verbose_name='Adjunta Imagen Visor'),
        ),
        migrations.AlterField(
            model_name='visor',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to='Visor', verbose_name='Adjunta Imagen Visor'),
        ),
        migrations.AlterField(
            model_name='visor',
            name='imagen3',
            field=models.ImageField(blank=True, null=True, upload_to='Visor', verbose_name='Adjunta Imagen Visor'),
        ),
        migrations.AlterField(
            model_name='visor',
            name='imagen4',
            field=models.ImageField(blank=True, null=True, upload_to='Visor', verbose_name='Adjunta Imagen Visor'),
        ),
        migrations.AlterField(
            model_name='visor',
            name='imagen5',
            field=models.ImageField(blank=True, null=True, upload_to='Visor', verbose_name='Adjunta Imagen Visor'),
        ),
        migrations.AlterField(
            model_name='visor',
            name='imagen6',
            field=models.ImageField(blank=True, null=True, upload_to='Visor', verbose_name='Adjunta Imagen Visor'),
        ),
    ]
